[versions]
#Versioning
#version_code = 1
#version_name = '0.0.0'
#build_tools = '30.0.3'

#Sdk and tools
compile_sdk = "36"
target_sdk = "36"
min_sdk = "26"

#Kotlin
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
ktx = '1.17.0'
coroutines = "1.10.2"

#Compose
composeBom = "2025.12.00"
compose_activity = "1.12.1"
compose_foundation = "1.10.0"
compose_paging = "3.3.6"
compose_lifecycle = "2.10.0"

#Android dependencies
lifecycle = "2.10.0"
room = "2.8.4"
navigation = "2.9.6"
palette = '1.0.0'

#Material Design
material3 = "1.4.0"
splashscreen = "1.2.0"

#Di
dagger_android = "1.2.0"
koin-bom = "4.1.1"

#Ktor
ktor_bom = "3.3.3"
ktor = "3.3.3"

#Tools
timber = '5.0.1'
serialization = "1.9.0"
desugar_jdk = "2.1.5"
secrets = "2.0.1"
coil = "3.3.0"
browser = "1.9.0"

#Testing
junit = "4.13.2"
junitVersion = "1.3.0"
junit_android = '1.1.3'
test_core = '1.4.0'
espresso = '3.7.0'
testRunner = '1.7.0'
mockito = '5.4.0'
testCoreAux = "1.7.0"
testCoreKtx = "1.7.0"
kotlinxCoroutinesTest = "1.10.2"
turbine = "1.2.1"
truth = "1.4.5"

# Plugins
agp = "8.13.2"
jetbrainsKotlinJvm = "2.2.21"
uiTextGoogleFonts = "1.10.0"
coreTesting = "2.2.0"
androidxAppcompatAppcompat = "1.7.1"
googleMaterialVersion = "1.13.0"

[libraries]

#Kotlin
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

#Android
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

#Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose_activity" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose_lifecycle" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose_foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }

#Navigation
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

#Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }

#Network
io-ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor_bom" }
io-ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
io-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
io-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
io-ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
io-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
io-ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth" }

#Room
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

#Tools
jakewharton-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
io-coil-kt = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
io-coil-kt-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

#Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin-bom" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-bom" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "testCoreKtx" }
androidx-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
io-ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
mockito = { module = "org.mockito.kotlin: mockito-kotlin", version.ref = "mockito"}
cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-foundation",
    "androidx-compose-icons-extended",
    "androidx-lifecycle-compose",
    "androidx-navigation"
]
koin = [
    "koin-core",
    "koin-android",
    "koin-androidx-compose",
    "koin-compose-navigation"
]
room = [
    "androidx-room",
    "androidx-room-common",
    "androidx-room-paging"
]
ktor = [
    "io-ktor-client-core",
    "io-ktor-client-okhttp",
    "io-ktor-client-content-negotiation",
    "io-ktor-client-auth",
    "io-ktor-client-logging",
    "io-ktor-serialization-kotlinx-json"
]
coil = [
    "io-coil-kt",
    "io-coil-kt-network"
]
local-tests = [
    "junit",
    "truth",
    "kotlinx-coroutines-test",
    "koin-test-junit4",
    "koin-test",
    "io-ktor-client-mock",
    "cash-turbine",
    "mockito"
]

instrumented-tests = [
    "truth",
    "androidx-junit",
    'androidx-compose-ui-test-manifest',
    "androidx-ui-test-junit4",
    "androidx-core-testing",
    "core-ktx",
    "androidx-runner",
    "kotlinx-coroutines-test",
    "androidx-espresso-core",
    "koin-test-junit4",
    "koin-test",
    "cash-turbine",
    "mockito"
]